// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC3NeJq6oo0HTDXvyVqCYfmxBtQJw5fII',
    appId: '1:221741911632:web:5130a2bbacd86f301e0b55',
    messagingSenderId: '221741911632',
    projectId: 'friday-a4cf3',
    authDomain: 'friday-a4cf3.firebaseapp.com',
    databaseURL: 'https://friday-a4cf3-default-rtdb.firebaseio.com',
    storageBucket: 'friday-a4cf3.appspot.com',
    measurementId: 'G-Z0B50NNMVW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNmd_KynaVdX3cas1eAbhl32WdMFkp13A',
    appId: '1:221741911632:android:cbeda3c8496f2d111e0b55',
    messagingSenderId: '221741911632',
    projectId: 'friday-a4cf3',
    databaseURL: 'https://friday-a4cf3-default-rtdb.firebaseio.com',
    storageBucket: 'friday-a4cf3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1HLCOKKFphwrhaAjLuc6PGXWlBnzp29I',
    appId: '1:221741911632:ios:a3ef4e7eb9d636ae1e0b55',
    messagingSenderId: '221741911632',
    projectId: 'friday-a4cf3',
    databaseURL: 'https://friday-a4cf3-default-rtdb.firebaseio.com',
    storageBucket: 'friday-a4cf3.appspot.com',
    iosBundleId: 'com.example.github',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1HLCOKKFphwrhaAjLuc6PGXWlBnzp29I',
    appId: '1:221741911632:ios:208f567e5a0f2e2f1e0b55',
    messagingSenderId: '221741911632',
    projectId: 'friday-a4cf3',
    databaseURL: 'https://friday-a4cf3-default-rtdb.firebaseio.com',
    storageBucket: 'friday-a4cf3.appspot.com',
    iosBundleId: 'com.example.github.RunnerTests',
  );
}
